# Generated by Django 5.0.4 on 2024-04-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino'), ('administrador', 'Administrador')], max_length=50)),
                ('num_identificacion', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
    ]
