# Generated by Django 5.0.4 on 2024-04-10 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_propiedad', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('medidas', models.CharField(max_length=100)),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('edificio', 'Edificio'), ('local_comercial', 'Local Comercial')], max_length=50)),
                ('descripcion', models.TextField()),
                ('estatus', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_arrendadas', to='usuarios.usuario')),
                ('inquilino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_alquiladas', to='usuarios.usuario')),
            ],
        ),
    ]
